FROM ubuntu:20.04

RUN dpkg --add-architecture i386 && \
	apt update && \
	DEBIAN_FRONTEND=noninteractive apt install -y \
		build-essential \
		ccache \
		chrpath \
		cpio \
		csh \
		curl \
		diffstat \
		gawk \
		gcc-multilib \
		git-core \
		jq \
		locales \
		libtinfo5 \
		lz4 \
		python \
		python3 \
		python3-pip \
		screen \
		socat \
		sudo \
		texinfo \
		unzip \
		vim \
		wget \
		zstd && \
	apt clean && rm -rf /var/lib/apt/lists/*

RUN pip install kas==4.6

COPY entrypoint.sh /
ENTRYPOINT [ "/entrypoint.sh" ]

RUN useradd -U -m builder -s /bin/bash && \
	locale-gen en_US.UTF-8
ENV LANG=en_US.UTF-8
